POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Kangaroos",
    "author": "Steven Cranley",
    "url": "stevencranley.com/blogs/kangaroos",
    "likes": 1400
}

###

GET http://localhost:3001/api/blogs