POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Growing up in Straboe",
    "author": "Oisin Cummins",
    "url": "oisincummins.com/blogs/straboe",
    "likes": "100"
}