POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Parrots",
    "author": "Steven Cranley",
    "url": "stevencranley.com/blogs/parrots",
    "likes": 1300
}

###

GET http://localhost:3001/api/blogs