POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "StevenCC",
    "name": "StevenC",
    "password": "Finnman",
    "blogs": ["64ea03764bf4757b3f32d2b2"]
}

###
GET http://localhost:3001/api/users